### PR TITLE
Refactor `SeedlingParPatch` to avoid code duplication

### PR DESCRIPTION
**Pull request by glemieux**
### Description:
This pull request refactors the `SeedlingParPatch` subroutine to avoid duplication of the calculation of `par` and `area` code.  It combines the `upper` and `lower` parts of the code by nesting it into a loop and reworking the check to see if there is more than a single canopy layer.

### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [ ] FATES PASS/FAIL regression tests were run
- [ ] If answers were expected to change, evaluation was performed and provided

### Test Results:

CTSM (or) E3SM (specify which) test hash-tag:

CTSM (or) E3SM (specify which) baseline hash-tag:

FATES baseline hash-tag:

Test Output:

### CODE REVIEW

**Comment by glemieux** [comment]
@adamhb I made this a PR to your PR branch since I thought it might be an easier way to double check that my refactor is doing what you initially intended.  I ran a quick single site smoke test and a 2 month exact restart test against the current commit on your `regeneration` branch and both results are b4b.

**Comment by adamhb** [comment]
Ok I see. Thank you @glemieux for getting this finalized. Let me know if there is anything else I can do!

**Comment by glemieux** [comment]
Thanks @adamhb.  Would you hit merge on this PR to merge it into your regeneration branch?

**Comment by adamhb** [comment]
Yes @glemieux, just merged it in.

**Pull request merged**
